vars.names = c(
  "Mon",
  "Tues",
  # "MonTue",
  "Wed",
  "Thur",
  "Fri",
  "Sat",
  # "workday",
  # "Mon2016",
  # "Tues2016",
  # "Wed2016",
  # "Thur2016",
  # "Fri2016",
  # "Sat2016",
  # "month1",
  # "month2",
  # "month3",
  # "month4",
  # "month5",
  # "month6",
  # "month7",
  # "month8",
  # "month9",
  # "month10",
  # "month11",
  # "month12",
  # "summer",
  # "autumn",
  # "y2015",
  # "y2016",
  # "holgroup",
  # "MotherDay",
  # "QueenBDay",
  # "HarmonyDay",
  # "HarmonyDay2015",
  # "AustraliaDay",
  # "ChristmasDay",
  # "NewYear",
  # "winter_holidays",
  # "GoodFridayDay",
  # "seasonality",
  # "TVsyn",
  # "TV15syn",
  # "EasterDay",
  # "LaborDay",
  # "MelbourneCupDay",
  # "startSchoolHoliday",
  # "endSchoolHoliday",
  # "FatherDay",
  # "ValentineDay",
  # "StPatrickDay",
  # "AnzackDay",
  "ext_comps_day",
  # "ext_comps_day2",
  # "ext_comps_day3",
  # "ext_comps_day4",
  # "ext_comps_day5",
  # "bs_comp1",
  "bs_comp2",
  # "issueUSEM", 
  # "USEM_spend2016",
  # "FB_Imps2014",
  # "issueBS_sp", 
  # "issueBS_imps",
  # "issueGDN", 
  # "brand_comp",
  #"trend",
  # "GDN_Imps",
  "GDN_spend",
  # "USEM_Imps",
  "USEM_spend",
  # "TV_imp",
  # "TV15_spend",
  "TV15_imp",
  # "TV30_imp",
  # "TV60_imp",
  "TV3060_imp",
  # "TV3060_spend",
  # "TV60_spend",
  "YouTube_Branding_imps",
  "YouTube_Performance_imps",
  # "YouTube_All_Imps",
  # "YouTube_Performance_spend",
  "Youtube_test_Imps",
  # "FB_Imps",
  "FB_spend"
  # "radio_spend"
  # "BS_Imps"
  # "BS_spend"
  
)