vars=c(
  "Mon",
  "Tues",
  # "MonTue",
  "Wed",
  "Thur",
  "Fri",
  "Sat",
  # "workday",
  # "Mon2016",
  # "Tues2016",
  # "Wed2016",
  # "Thur2016",
  # "Fri2016",
  # "Sat2016",
  # "month1",
  # "month2",
  # "month3",
  # "month4",
  # "month5",
  # "month6",
  # "month7",
  # "month8",
  # "month9",
  # "month10",
  # "month11",
  # "month12",
  # "summer",
  # "autumn",
  # "y2015",
  # "y2016",
  # "holgroup",
  # "MotherDay",
  # "QueenBDay",
  # "HarmonyDay",
  # "HarmonyDay2015",
  # "AustraliaDay",
  # "ChristmasDay",
  # "NewYear",
  # "winter_holidays",
  # "seasonality",
  # "TVsyn",
  # "TV15syn"
  # "GoodFridayDay",
  # "EasterDay",
  # "LaborDay",
  # "MelbourneCupDay",
  # "startSchoolHoliday",
  # "endSchoolHoliday",
  # "FatherDay",
  # "ValentineDay",
  # "StPatrickDay",
  # "AnzackDay",
  "ext_comps_day",
  # "ext_comps_day2",
  # "ext_comps_day3",
  # "ext_comps_day4",
  # "ext_comps_day5",
  # "bs_comp1",
  "bs_comp2",
  # "issueUSEM", 
  # "USEM_spend2016",
  # "FB_Imps2014",
  # "issueBS_sp", 
  # "issueBS_imps",
  # "issueGDN", 
  # "brand_comp",
  #"trend",
  # "Outliers",
  # "issue",
  # "USEM_Imps_2016",
  # "I(GDN_Imps^para[17])",
  
  "I(GDN_spend^para[1])",
  # "I(adstock(GDN_spend, para[13])^para[1])",
  
  # "I(USEM_Imps^para[13])",
  
  "I(USEM_spend^para[2])",
  # "I(adstock(USEM_spend, para[14])^para[2])",
  
  #"I(USEM_Imps^para[2])",
  # "I(adstock(TV_imp,para[3])^para[4])",
  "I(adstock(TV15_imp,para[3])^para[4])",
  # "I(adstock(TV15_spend,para[3])^para[4])",
  # "I(adstock(TV3060_spend,para[5])^para[6])",
  # "I(adstock(TV30_imp,para[5])^para[6])",
  # "I(adstock(TV60_imp,para[7])^para[8])",
  "I(adstock(TV3060_imp,para[5])^para[6])",
  "I(adstock(TV3060_imp,para[5])^para[6])*seasonality",
  "I(YouTube_Branding_imps^para[7])",
  "I(adstock(YouTube_Performance_imps,para[8])^para[9])",
  # "I(adstock(YouTube_All_Imps,para[8])^para[9])",
  # "I(adstock(YouTube_Performance_spend,para[10])^para[11])",
  "I(adstock(Youtube_test_Imps, para[10])^para[11])",
  # "Youtube_test_Imps",
  "I(FB_spend^para[12])"
  # "I(FB_Imps^para[14])",
  # "I(adstock(radio_spend,para[13])^para[14])"
  # "I(BS_spend^para[15])"
  # "I(BS_Imps^para[16])"
  # "I((p[11]*seasonality_2011 + (1-p[11])*seasonality_2012)^p[12])",
)
